---
dist: xenial

language: python
python: 3.7.1

cache:
  directories:
    - ~/.cache/pip
before_cache:
  - rm -rf ~/.cache/pip/log/

matrix:
  fast_finish: true
  include:
    - name: Python3.7 Tests
      env: TOXENV=py37, test-coverage

    - name: Python2.7 Tests
      env: TOXENV=py27

    - name: Style checks
      env: TOXENV=style

install: pip install -U pip tox codecov
script: tox
# Always report coverage, even if tests failed (or some tests were not run)
after_script:
  - codecov

# In addition to pull requests, always build these branches
branches:
  only:
  - master
  # Match tags starting with "vN..."
  - /^v\d+.*$/


# Deploy to CloudRepo PyPI for tags
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  server: https://goodrx.mycloudrepo.io/repositories/goodrx
  user: engineering-ops+travis-read-write@goodrx.com
  password:
    secure: "j5npzyO9wPkIcptrRfu5VWf/whXX44oYw+L9ii+9/oBIcuF/ZdsLMQ2ZDSa06bBOsdHTqlxv6Lb2rUCOKQGsqj4fb9hCDd8HUKI3FwPYpUq5WgMIW3Xf4sVdIBzOpd838iProtNpCMggrehYeqk4Odz1Wf+XMOpo2/dMmvRCkh/CobXfDSNXwU8kRxeMjN1zBL4pRvBIMdFY8aMuu2OxvF2yEMTS+eLAJ65OhwT3UF/3awli7kjpbS9zuSTYL7b6xJ7F0bDfIK3lQA9zZVX3LMj0khLe5JdJ6UaXusu++O4udOcTbQdc77QmwPugT6dAqsff6dKRQXcVSuCOPi7ldG+YnbHgFRwcq+KsqKomk3UMfS34cn/CswmOJsVPmn/TRNsi7ocyImGJ37eKrdwKB3A20tzgblOASiww31UHpkieBkHprTsSLWNmE2aQNoqkC9YjXKoVIbIR+EZVjPom9JJcUL9bhvxtFXp43spRHvm8b45n6vv2xW6zA93h1Sk4fpz43hi8fpBqxs7lC0Vgn2gIw9/gdPrL++hGemYgGSy1yj2bLlJ9rIRvDfMTr+zV9VG4LqwI0m9OQiZeyepS5IoOn2gYArsluynWKV7memB812Vli+AWBEmS37DQmFcAQkif/EnDGXsrz0JXhibig+v2IBmh+O/WRbVT1FOdhBU="
  "on":
    tags: true
