---
dist: xenial

language: python
python: 3.7.1

cache:
  directories:
    - ~/.cache/pip
before_cache:
  - rm -rf ~/.cache/pip/log/

matrix:
  fast_finish: true
  include:
    - name: Python3.7 Tests
      env: TOXENV=py37, test-coverage

    - name: Python2.7 Tests
      env: TOXENV=py27

    - name: Style checks
      env: TOXENV=style

    - name: Deploy to GoodRx PyPi
      stage: release
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        server: https://goodrx.mycloudrepo.io/repositories/goodrx
        user: engineering-ops+travis-read-write@goodrx.com
        password:
          secure: "lxobPl+3JS+XLv2TQWdx/KXGoU2Jv1SeaSAYcBL9qxYZo6aRcxJ8B+PJq63npkoG7AshS28d/NV2X95JA5rTalKgy+3jaHNZ2/31NKI3ZyKXtSU9FG0jDFOwR8N6PkkeIWqgXTL/0Os3upWpmmOBRPCVxt9/9MOgIQemz18OQ3UNuX4viaU3fMnDAD0vi4FzJRgpnPTIxXg8in+9IJ0WFtBwIR6GEwtEcXAK2J3ovfS6lYdR0Sn+0WnOuofjVjS2P3cNdqqGhsz6CaaZBnHToCHk2FMo39e1kiEi50wKqke2tW9roRHyUngkLH4l1tIwrV8Y/Ib4amRlt9zFKVpBmfFPiiGJ78y3WIdC/tfMbSw9ipd1sQn+4gq2qWd8GhPQNU3jWdG6gY06AMFWhudtJ4la0Xj+0dL2TFYGslZJQcZNV7t+EV6TQKQISvdQVwn097Jx13DdwGOfFbgTlAzvVfZiYipmwoZr3rPsrIq9NTbnF6ex+ckfwfsTLI8tl4WdmNTiO9aG3a2Tt8d3doMoupTvnnOB+auinL0dTwKfwgKWWL/+jsTIevfVZ1tKvsyrhcxsFT9aVDu2zfLR+GBNXtYIPf3OZjcUyEOIZpl2YXHFf5mFBsGW9lSB0fXnitj3lUE213h/8581ZVfWxa3Wsgxz5A3t7BE0OBfabOtfCxM="
        "on":
          tags: true


install: pip install -U pip tox codecov
script: tox
# Always report coverage, even if tests failed (or some tests were not run)
after_script:
  - codecov

# In addition to pull requests, always build these branches
branches:
  only:
    - master
    - /^v\d+.*$/
